Login/urls.py
from django.urls import path
from Login import views

urlpatterns = [
    path('', views.main, name='main'),
    path('register',views.register,name='register'),
    path('about', views.about, name='about'),
    path('logout', views.logout_view, name='logout'),

]

profiles/urls.py
from django.urls import path
from django import urls
from profiles import views
app_name = 'profiles'

urlpatterns = [
    path('', views.pro, name='pro'),
    path(r'^results/$', views.search_user,name="search"),
    path('update/',views.update_account,name="update"),
    path('friend_request',views.friend_request,name="friend request"),
    path('requests/',views.show_requests, name="show requests"),
    path('requests/accepted',views.accept_request,name="accept"),
    path('chat',views.show_friends,name="chat"),
    path('/room',views.create_chat_room,name="new_room"),
    path('chat/room/<uuid:room_name>',views.chat_room,name='chat_room'),

]

speakeasy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profiles.urls')),
]

profiles/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils import timezone
import uuid
from django.utils.crypto import get_random_string

# Create your models here.





class Profile(models.Model):
    Languages=[
     ('EN','English'),
     ('ZH','Chinese'),
     ('HI','Hindi'),
     ('ES','Spanish'),
     ('FR','French'),
     ('AR','Arabic'),
     ('RU','Russian'),
     ('BN','Bengali'),
     ('PT','Portuguese'),
     ('ID','Indonesian'),
      ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    Lang_Pref = models.CharField(max_length=2, choices=Languages,default='EN')


    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()





class Relationship(models.Model):
    type = models.TextField(max_length=50,blank=True)
    profile = models.ForeignKey(Profile,related_name='relationships', on_delete=models.CASCADE)
    #





class People(models.Model):
    friend_id=models.PositiveIntegerField(null=True, blank=True)
    rel_id= models.ForeignKey(Relationship,related_name='people',on_delete=models.CASCADE)

class requests(models.Model):
    receiver=models.ForeignKey(User,related_name='requests',on_delete=models.CASCADE)
    sender=models.PositiveIntegerField(null=False,blank=False)
    accepted=models.BooleanField(null=False,default=False,blank=False)


@receiver(post_save,sender=requests)
def create_user_relationships(sender, instance, **kwargs):
    #if the instance of request is accepted
    if instance.accepted==True:
        #set the current user
        current_user=User.objects.get(id=instance.receiver.id)
        #set the sender
        oth_user=User.objects.get(id=instance.sender)

        #create the relationships
        user_rel= Relationship.objects.create(type='friend',profile=current_user.profile)
        user_rel.save()
        oth_rel=Relationship.objects.create(type='friend',profile=oth_user.profile)
        oth_rel.save()
        #create the people

        user_peep= People.objects.create(friend_id=oth_user.id,rel_id=user_rel)
        user_peep.save()
        oth_peep=People.objects.create(friend_id=current_user.id,rel_id=oth_rel)
        oth_peep.save()




"""Chat models for the user"""

class Room(models.Model):
    room_name = models.UUIDField(default=uuid.uuid4,editable=False,unique=True,null=False,blank=False)
    user_1 = models.PositiveIntegerField(null=False,blank=False)
    user_2 = models.PositiveIntegerField(null=False,blank=False)


class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages',on_delete=models.CASCADE)
    handle = models.TextField()
    message = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)


# @receiver(post_save,sender=Room)
# def create_user_room(sender, instance, **kwargs):
#     if instance.user_1 and instance.user_2:
#         instance.room_name = get_random_string(length=32)
#         instance.save()

profiles/forms.py
from django.forms import ModelForm
from .models import User,Profile




class InfoForm(ModelForm):
    class Meta:
        model= Profile
        fields=['bio','location','birth_date','Lang_Pref']
    # bio = forms.CharField(label='Bio', max_length=500)
    # location = forms.CharField(label='Location', max_length=30)
    # birth = forms.DateField(label='Date of Birth')

profiles/views.py
from django.shortcuts import render,redirect
from speakeasy.config import pagination
from django.db.models import Q
from django.urls import reverse,reverse_lazy
from .models import User,requests,Relationship,People,Room,Message
from .forms import InfoForm
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.utils.crypto import get_random_string
from django.utils.safestring import mark_safe
import json
from . import trans_mover

# Create your views here.

def pro(request):


    return render(request, 'main/pro.html',{})



def search_user(request):

    ##Template for the main page
    template = 'main/post_list.html'
    # Query by user
    query = request.GET.get("q")
    if query:
        #results of query from Users table to database
        results= User.objects.filter(
        Q(username__icontains=query)|
        Q(last_name__icontains=query)|
        Q(first_name__icontains=query)
        ).distinct()
    else:
        #if no query return users with 'a' in name
        results = User.objects.filter(Q(username__icontains="a"))

    pages=pagination(request,results,num=10)
    context={'items':pages[0],
    'page_range': pages[1],
    'query': query,
     }
    return render (request,template,context)



def update_account(request):

    if request.user.is_authenticated:
        if request.method=='POST':
            #create new instance of form
            form= InfoForm(request.POST, instance=request.user.profile)

            if form.is_valid():
                    print("made it here")
                    #save user profile

                    form.save()
                    print("made it here")
                    #redirect to profile
                    return HttpResponseRedirect('/profile/')
            else:
                print(form.errors)
                return HttpResponse("form not valid")
        else:

            #if its not a post method create a new info form
            form= InfoForm(instance=request.user.profile)
            #this is to access form variable from view
            context= {'form': form}
            #return the html file to user with rendered form as context
            return render(request,'main/update.html',context)
    else:
            return HttpResponseRedirect('/accounts/login')



def friend_request(request):
    #get the user you want to send a request to from the post method
    other_user=request.POST.get("oth_user")
    #get the current user making the request
    current_user = request.user.id

    #if they aren't the same person save the data in database and redirect to profile
    if other_user != current_user:
        new_request=requests()
        new_request.sender=current_user
        new_request.receiver=User.objects.get(id=other_user)
        new_request.accepted=False
        new_request.save()
        return HttpResponseRedirect('/profile/')


def show_requests(request):
    #set the template
    template='main/requests.html'
    #Set friend name empty
    friend_name=None
    #get the user making the request
    current_user =request.user

    #if there is a request filter all requests down to the current user
    friend_req= requests.objects.filter(receiver=current_user.id,accepted=False)
    #loop through the requests and find senders name based off of ID
    #set names equal to friend names
    if friend_req:
        for f in friend_req:
            friend_name= User.objects.filter(id=f.sender)

    #if there are friends show the friends and paginate
    if friend_name != None:
        pages=pagination(request,friend_name,num=10)
        #find = lambda a: User.objects.get(id=a)
        context={'items':pages[0],
        'page_range': pages[1],
         }
        return render (request,template,context)
    #if there are no friends return only the template
    else:
        return render(request,template,{})


def accept_request(request):
        #get the user you want to send a request to from the post method
        other_user=request.POST.get("oth_user")
        #get the current user making the request
        current_user = request.user.id
        friend_requests = requests.objects.get(sender=other_user,receiver=current_user)
        #if they aren't the same person save the data in database and redirect to profile
        if friend_requests:
            friend_requests.accepted=True
            friend_requests.save()
            return HttpResponseRedirect('/profile/requests/')



def show_friends(request):
            peeps=[]
            friends=[]
            template='main/chat.html'
            #get the current user
            current_user= request.user
            #get the users relationships
            relationship = Relationship.objects.filter(profile=current_user.profile)
            #find the people in the relationship
            for rel in relationship:
                peeps = rel.people.all()
                #match the people to the user
                for p in peeps:
                    friends+=User.objects.filter(id=p.friend_id)




            if friends!=None:
                print(friends)
                pages=pagination(request,friends,num=20)
                context={'items':pages[0],
                'page_range': pages[1],
                 }
                return render (request,template,context)
            #if there are no friends return only the template
            else:
                return render(request,template,{})




def create_chat_room(request):
    #Get the current user & the User we want to send messages to #
    user1= request.user
    user2=request.POST.get("oth_user")

    # If the room with the given users doesn't exist, automatically create it
    # upon first visit
    try:
        room = Room.objects.get(user_1__in=[user1.id,user2],user_2__in=[user1.id,user2])
    except:
        new_room = Room.objects.create(user_1=user1.id,user_2=user2)
        #create new room and render it
        return redirect(reverse_lazy('profiles:chat_room',  kwargs={'room_name': new_room.room_name}))


    if Room.objects.filter(room_name=room.room_name).exists():
        #render existing room
        return redirect(reverse_lazy('profiles:chat_room',  kwargs={'room_name': room.room_name}))
    else:
        new_room = Room.objects.create(user_1=user1.id,user_2=user2)
        #create new room and render it
        return redirect(reverse_lazy('profiles:chat_room',  kwargs={'room_name': new_room.room_name}))



def chat_room(request,room_name):
        room= Room.objects.get(room_name=room_name)



        if request.user.is_authenticated and room.user_1==request.user.id or room.user_2==request.user.id:

            #get the last 50 messages
            messages = reversed(room.messages.order_by('-timestamp')[:50])





            translation= trans_mover.translate(get_txt(room_name))
            #render the room with the user objects inside of them
            current_user= request.user
            oth_user= None
            if current_user.id == room.user_1:
                oth_user= User.objects.get(id=room.user_2)
            else:
                oth_user=User.objects.get(id=room.user_1)
            return render(request, "main/room.html", {
                'room': room,
                'messages': messages,
                'user': current_user,
                'friend': oth_user,
                'translations': translation
            })
        else:
            return render(request,"error/404.html",{})

def get_txt(room_name):
    room= Room.objects.get(room_name=room_name)
    untranslated=[]
    messages = reversed(room.messages.order_by('-timestamp')[:50])
    for msg in messages:
        untranslated.append(msg.message)

    return untranslated

profiles/templates/main/chat.html
{%extends "pro.html"%}


{% block page_content %}
<div class="d-flex justify-content center">
<div class="d-flex flex-column">
  <div class="card" style="width: 90rem; margin:60px; border-radius:25px;">
  <ul class="list-group list-group-flush" style="margin-left:auto; margin-right:auto;">
    <h1>Chat with Friends</h1>
{%for obj in items%}

    <li class="list-group-item" style="text-align: left;"><h2> </br>Name:{{obj.first_name}} {{obj.last_name}} </br> Location: {{obj.profile.location}} </br>
    </br>Bio:{{obj.profile.bio}}
      {%if user.is_authenticated%}
      <form method="POST" action="{% url 'profiles:new_room' %}">
        {% csrf_token %}
        <input name="oth_user" value="{{obj.id}}" hidden>
      <button type="submit" class="btn btn-outline-success"><i class="far fa-comments"><sup>Chat</sup></i></button>
    </form>
      {%endif%}</h2> </li>

{% endfor %}
</ul>
</div>

<div style="margin-left: auto; margin-right:auto;" >
{% include "pagination.html" %}
</div>
</div>
{% endblock %}

profiles/templates/main/post_list.html
{%extends "base.html"%}


{% block page_content %}
<div class="d-flex justify-content center">
<div class="d-flex flex-column">
<form style="margin-left:auto; margin-right:auto; padding-top:50px;" method="GET" action="{% url 'profiles:search' %}"class="form-inline my-2 my-lg-0">
  <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{request.Get.query}}">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
  <div class="card" style="width: 90rem; margin:60px; border-radius:25px;">
  <ul class="list-group list-group-flush" style="margin-left:auto; margin-right:auto;">
{%for obj in items %}

    <li class="list-group-item" style="text-align: left;"><h2>{{obj.username}}{{obj.id}} </br>Name:{{obj.first_name}} {{obj.last_name}} </br> Location: {{obj.profile.location}} </br>
      {%if user.is_authenticated and user.id != obj.id%}
      <form method="POST" action="{% url 'profiles:friend request' %}">
        {% csrf_token %}
        <input name="oth_user" value="{{obj.id}}" hidden>
      <button type="submit" class="btn btn-outline-success"><i class="fas fa-user-plus"><sup>add friend</sup></i></button>
    </form>
      {%endif%}</h2> </li>

{% endfor %}
</ul>
</div>

<div style="margin-left: auto; margin-right:auto;" >
{% include "pagination.html" %}
</div>
</div>
{% endblock %}

profiles/templates/main/pro.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #0C29E6;">

  <a class="navbar-brand" href="/">SpeakEasy</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
         <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="/about">About</a>
       </li>
       {%if user.is_authenticated%}
       <li class="nav-item dropdown">

         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           profile
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="/profile">profile</a>
           <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="/logout">Logout</a>
         </div>
       </li>
      {%else%}
      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Login/Sign-Up
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/accounts/login">Login</a>
          <a class="dropdown-item" href="/register">Sign-up</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/logout">Logout</a>
        </div>
      </li>
      {%endif%}
     </ul>
     <form method="GET" action="{% url 'profiles:search' %}"class="form-inline my-2 my-lg-0">
       <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{request.Get.query}}">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
   </div>
 </nav>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{%load static%}
<link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

{%if user.is_authenticated%}


<!-- <div id="wrapper" style=" background-size: auto;background-image:url({% static "images/background2.png" %})"> -->
<div id="wrapper" style="background-size:auto;" >
  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3"> <sup>{{user.username}}</sup></div>
    </br>
    </a>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Bio: </br>{{user.profile.bio}}</p></div>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Location:</br> {{user.profile.location}}</p></div>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Birthday:</br> {{user.profile.birth_date}}</p></div>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Speaks:</br> {{user.profile.Lang_Pref}}</p></div>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="/profile">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Home</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Interact
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="{%url 'profiles:chat' %}">
        <i class="fas fa-fw fa-cog"></i>
        <span> Chat</span>
      </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-wrench"></i>
        <span>Video</span>
      </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">

    </div>



    <!-- Nav Item - Charts -->
    <li class="nav-item">
      <a class="nav-link" href="requests">
        <i class="fas fa-fw fa-chart-area"></i>

        <span>requests</span></a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="update">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Settings</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="/logout">
        <i class="fas fa-fw fa-table"></i>
        <span>Logout</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div class="row" style="margin-left:auto; margin-right:auto;">
  <!--<div class="col align-self-center">-->
<h1></h1>
{% block page_content %}{% endblock %}
<h1>Pages go here</h1>
</div>
</div>
</div>

<!-- Bootstrap core JavaScript-->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

 <!-- Core plugin JavaScript -->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

 <!-- Custom scripts for all pages -->
<script src="js/sb-admin-2.min.js"></script>

 <!-- Page level plugins -->
<script src="vendor/chart.js/Chart.min.js"></script>

 <!-- Page level custom scripts -->
<script src="js/demo/chart-area-demo.js"></script>
<script src="js/demo/chart-pie-demo.js"></script>

{%else%}
<p><h1> 404 Error <br> *obi-wan handwave these are not the pages you are looking for</h1></p>
{%endif%}

profiles/templates/main/requests.html
{%extends "pro.html"%}


{% block page_content %}
<div class="d-flex justify-content center">
<div class="d-flex flex-column">
  <div class="card" style="width: 90rem; margin:60px; border-radius:25px;">
  <ul class="list-group list-group-flush" style="margin-left:auto; margin-right:auto;">
{%for obj in items %}

    <li class="list-group-item" style="text-align: left;"><h2> </br>Name:{{obj.first_nam}} {{obj.last_name}} </br> Location: {{obj.profile.location}} </br>
      {%if user.is_authenticated%}
      <form method="POST" action="{% url 'profiles:accept' %}">
        {% csrf_token %}
        <input name="oth_user" value="{{obj.id}}" hidden>
      <button type="submit" class="btn btn-outline-success"><i class="fas fa-user-plus"><sup>accept request</sup></i></button>
    </form>
      {%endif%}</h2> </li>

{% endfor %}
</ul>
</div>

<div style="margin-left: auto; margin-right:auto;" >
{% include "pagination.html" %}
</div>
</div>
{% endblock %}

profiles/templates/main/update.html
{%extends "pro.html"%}
{% block page_content %}
{%if user.is_authenticated %}
<div class="container" >
  <div class="row">
    <div class="col align-self-center">

    <h5 class="display-4" >Update your account </br>
    <h1><i class="far fa-user-circle"></i></h1></h5>
    {%if form.errors%}
    <p style="color: red">Please fill all inputs!</p>
    {%endif%}
    <form method="post" action="{%url 'profiles:update'%}">
      {% csrf_token %}


      <div class="form-group" >
        <label for="Bio">Bio:</br> {{form.bio}}</label>
      </div>

  <div class="form-group">
    <label for="Location">Location:</br>{{form.location}}</label>
    </div>

  <div class="form-group">
    <label for="Birth">Birthday(DD/MM/YY):</br>{{form.birth_date}}</label>
    </div>
    <div class="form-group">
      <label for="Lang_Pref">Language preference:</br>{{form.Lang_Pref}}</label>
      </div>
  <button type="submit" class="btn btn-primary" value="login">Submit</button>
  <input type="hidden" name="next" value="{{next}}">
</form>

  </div>
</div>
</div>

{%else%}

<p><h1> 404 Error <br> *obi-wan handwave these are not the pages you are looking for</h1></p>
{%endif%}


{% endblock %}