Login/urls.py
from django.urls import path
from Login import views

urlpatterns = [
    path('', views.main, name='main'),
    path('register',views.register,name='register'),
    path('about', views.about, name='about'),
    path('logout', views.logout_view, name='logout'),

]

profiles/urls.py
from django.urls import path
from django import urls
from profiles import views
app_name = 'profiles'

urlpatterns = [
    path('', views.pro, name='pro'),
    path(r'^results/$', views.search_user,name="search"),
    path('update/',views.update_account,name="update"),
    path('friend_request',views.friend_request,name="friend request"),
    path('requests/',views.show_requests, name="show requests"),
    path('requests/accepted',views.accept_request,name="accept"),
    path('chat',views.show_friends,name="chat"),
    path('/room',views.create_chat_room,name="new_room"),
    path('chat/room/<uuid:room_name>',views.chat_room,name='chat_room'),

]

speakeasy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('profiles.urls')),
]

speakeasy/templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #0C29E6;">

  <a class="navbar-brand" href="/">SpeakEasy</a>
   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
         <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="/about">About</a>
       </li>
       {%if user.is_authenticated%}
       <li class="nav-item dropdown">

         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           profile
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="{% url 'profiles:pro' %}">profile</a>
           <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="/logout">Logout</a>
         </div>
       </li>
      {%else%}
      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Login/Sign-Up
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/accounts/login">Login</a>
          <a class="dropdown-item" href="/register">Sign-up</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      {%endif%}
     </ul>
     <form method="GET" action="{% url 'profiles:search' %}"class="form-inline my-2 my-lg-0">
       <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{request.Get.query}}">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
   </div>
 </nav>
{% block page_content %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

speakeasy/templates/pagination.html
<div class="col-md-6 text-left">
    {% if items.has_other_pages %}
            <div class="btn-group" >
            {% if items.has_previous %}
              <button type="button" class="btn btn-default btn-md page-first" onclick="location.href='?pagenumber=1&limit={{rows}}';">First</button>
              <button type="button" class="btn btn-default btn-md page-arrows" onclick="location.href='?pagenumber={{ items.previous_page_number }}&limit={{rows}}{%if query%}&q={{query}}{%endif%}';">&laquo;</button>
            {% else %}
              <button type="button" class="btn disabled" >First</button>
              <button type="button"  class="btn disabled">&laquo;</button>

            {% endif %}
                </div>
    <span><b>Page </b></span>
            <input type="text" style="width:50px" onchange="location.href='?pagenumber={{items.number}}&limit={{rows}}{%if query%}&q={{query}}{%endif%}';" onkeyup="this.onchange()" oninput="this.onchange()" value="{{items.number}}" >
                <span> of {{items.paginator.num_pages}}</span>


             <div class="btn-group" >
            {% if items.has_next %}

              <button type="button"  class="btn btn-default btn-md page-arrows"  onclick="location.href='?pagenumber={{ items.next_page_number }}&limit={{rows}}{%if query%}&q={{query}}{%endif%}';">&raquo;</button>
              <button type="button"  class="btn btn-default btn-md page-last" onclick="location.href='?pagenumber={{ items.paginator.num_pages }}&limit={{rows}}{%if query%}&q={{query}}{%endif%}';">Last</button>
            {% else %}

              <button type="button"  class="btn btn disabled">&laquo;</button>
                <button type="button" class="btn disabled" >Last</button>

            {% endif %}
             </div>

    {% endif %}


</div>

speakeasy/templates/pro.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #0C29E6;">

  <a class="navbar-brand" href="/">SpeakEasy</a>
   </button>

   <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
         <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="/about">About</a>
       </li>
       {%if user.is_authenticated%}
       <li class="nav-item dropdown">

         <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           profile
         </a>
         <div class="dropdown-menu" aria-labelledby="navbarDropdown">
           <a class="dropdown-item" href="/profile">profile</a>
           <div class="dropdown-divider"></div>
           <a class="dropdown-item" href="/logout">Logout</a>
         </div>
       </li>
      {%else%}
      <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Login/Sign-Up
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/accounts/login">Login</a>
          <a class="dropdown-item" href="/register">Sign-up</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
      {%endif%}
     </ul>
     <form method="GET" action="{% url 'profiles:search' %}"class="form-inline my-2 my-lg-0">
       <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search" value="{{request.Get.query}}">
       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
     </form>
   </div>
 </nav>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

{%load static%}
<link href="{% static 'css/sb-admin-2.min.css'%}" rel="stylesheet">

{%if user.is_authenticated%}


<!-- <div id="wrapper" style=" background-size: auto;background-image:url({% static "images/background2.png" %})"> -->
<div id="wrapper" style="background-size:auto;" >
  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3"> <sup>{{user.username}}</sup></div>
    </br>
    </a>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Bio: </br>{{user.profile.bio}}</p></div>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Location:</br> {{user.profile.location}}</p></div>

<div class="sidebar-brand-text mx-3"><p style="color: black;">Birthday:</br> {{user.profile.birth_date}}</p></div>
<div class="sidebar-brand-text mx-3"><p style="color: black;">Speaks:</br> {{user.profile.Lang_Pref}}</p></div>
    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <a class="nav-link" href="/profile">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Home</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Interact
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="/profile/chat" >
        <i class="fas fa-fw fa-cog"></i>
        <span> Chat</span>
      </a>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
        <i class="fas fa-fw fa-wrench"></i>
        <span>Video</span>
      </a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">

    </div>



    <!-- Nav Item - Charts -->
    <li class="nav-item">
      <a class="nav-link" href='/profile/requests'>
        <i class="fas fa-fw fa-chart-area"></i>
        <span>requests</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/profile/update">
        <i class="fas fa-fw fa-chart-area"></i>
        <span>Settings</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="/logout">
        <i class="fas fa-fw fa-table"></i>
        <span>Logout</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div class="row" style="display: flex;margin-left:auto; margin-right:auto;" >
  <!--<div class="col align-self-center">-->
<h1></h1>
{% block page_content %}{% endblock %}

</div>
</div>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

 <!-- Core plugin JavaScript -->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

 <!-- Custom scripts for all pages -->
<script src="js/sb-admin-2.min.js"></script>

 <!-- Page level plugins -->
<script src="vendor/chart.js/Chart.min.js"></script>

 <!-- Page level custom scripts -->
<script src="js/demo/chart-area-demo.js"></script>
<script src="js/demo/chart-pie-demo.js"></script>

{%else%}
<p><h1> 404 Error <br> *obi-wan handwave these are not the pages you are looking for</h1></p>
{%endif%}